import Image from "next/image";
import Link from "@/components/navigation-link";
import { Brand, Icon } from "@/components/ui";

const benefits = [["alerts", "Fewer surprises", "Catch developing issues before they become major disruptions."], ["user", "Clearer priorities", "Focus on the equipment that needs attention first."], ["arrow", "Faster response", "Move from alert to maintenance work without disconnected processes."], ["reports", "Better visibility", "A shared view of equipment health, maintenance activity and outstanding work."]] as const;
const steps = [["alerts", "Spot", "See which equipment needs attention."], ["monitoring", "Understand", "Know what changed and why it matters."], ["arrow", "Act", "Turn an issue into maintenance work."], ["reports", "Stay ahead", "Follow the work through to completion."]] as const;

export default function LandingPage() {
  return <main className="landing-v2">
    <header className="landing-v2-nav"><Link className="landing-v2-brand" href="/"><Brand /></Link><nav aria-label="Primary navigation"><a href="#home">Home</a><a href="#how-it-works">How It Works</a><a href="#benefits">Benefits</a><a href="#features">Features</a><a href="#about">About</a></nav><Link className="landing-v2-signin" href="/login">Sign In →</Link></header>
    <section className="landing-v2-hero" id="home"><div className="landing-v2-hero-copy"><span className="landing-kicker">SMARTER MAINTENANCE. STRONGER OPERATIONS.</span><h1>Know What Needs Attention. Before It <em>Becomes Downtime.</em></h1><p>MaintainNexus helps maintenance teams spot equipment issues early, prioritize what matters, and coordinate the right response — all from one place.</p><div className="landing-v2-actions"><Link className="landing-v2-primary" href="/login">See How It Works →</Link><Link className="landing-v2-outline" href="/login">Sign In</Link></div><div className="landing-proof"><span><Icon name="audit" /><b>More Reliable<br />Operations</b></span><span><Icon name="user" /><b>Empowered<br />Teams</b></span><span><Icon name="reports" /><b>A Cleaner<br />Tomorrow</b></span></div></div><div className="landing-v2-hero-art"><Image src="/images/landing/industrial-hero.png" alt="Industrial facility at sunrise" fill priority sizes="(max-width: 900px) 100vw, 58vw" /><div className="landing-v2-laptop"><div className="laptop-top"><Brand /><span>Sign in for live data</span></div><div className="laptop-body"><aside><b>MaintainNexus</b><span>⌂ Dashboard</span><span>⌁ Live Monitoring</span><span>▣ Equipment</span><span>♧ Alerts</span><span>▤ Work Orders</span></aside><div><h3>Hello Vertex</h3><small>Sign in to view your authorized equipment data.</small><div className="preview-stats"><b>&mdash;<small>Equipment</small></b><b>&mdash;<small>Active Alerts</small></b><b>&mdash;<small>Open Work Orders</small></b><b>&mdash;<small>Uptime</small></b></div><div className="preview-panels"><div><strong>Equipment Health</strong><p>Sign in to view recorded equipment health.</p></div><div><strong>Recent Alerts</strong><p>Sign in to view recorded alerts.</p></div></div></div></div></div></div></section>
    <section className="landing-challenge" id="about"><div><span className="landing-kicker">THE CHALLENGE</span><h2>Maintenance shouldn’t start with a breakdown.</h2><p>When equipment issues go unnoticed, a small problem can quickly turn into downtime, costly repairs and disrupted operations. MaintainNexus gives you an earlier view of what needs attention so you can act with confidence.</p></div><div className="challenge-steps"><article><Icon name="alerts" /><h3>A problem<br />develops</h3><p>Small issues can be easy to miss.</p></article><b>→</b><article><Icon name="search" /><h3>We spot it<br />earlier</h3><p>Important changes are brought to your attention.</p></article><b>→</b><article><Icon name="arrow" /><h3>Your team<br />acts early</h3><p>Maintenance gets moving before it becomes downtime.</p></article></div></section>
    <section className="landing-how" id="how-it-works"><div className="landing-how-heading"><span className="landing-kicker">HOW IT WORKS</span><h2>From warning to action —<br />without the guesswork.</h2></div><div className="landing-step-row">{steps.map(([icon, title, text]) => <article key={title}><Icon name={icon} /><h3>{title}</h3><p>{text}</p></article>)}</div></section>
    <section className="landing-benefits" id="benefits"><div className="landing-section-heading"><div><span className="landing-kicker">BUILT FOR IMPACT</span><h2>Keep your operations moving.</h2></div><p>MaintainNexus helps you get more value from your assets, your people and your time.</p></div><div className="landing-benefit-grid">{benefits.map(([icon, title, text]) => <article key={title}><Icon name={icon} /><div><h3>{title}</h3><p>{text}</p></div></article>)}</div></section>
    <section className="landing-results" id="features"><div><span className="landing-kicker">REAL RESULTS</span><h2>Stronger assets.<br />More possible.</h2><p>When your equipment runs reliably, your people can do their best work — and your operations can move forward with confidence.</p><Link className="landing-v2-primary" href="/login">See MaintainNexus in Action →</Link></div><div className="landing-image-grid"><article><Image src="/images/landing/technician-inspection.png" alt="Technician inspecting industrial equipment" fill sizes="33vw" /><b>Assets</b><span>Running reliably.</span></article><article><Image src="/images/landing/team-collaboration.png" alt="Maintenance team collaborating" fill sizes="33vw" /><b>People</b><span>Working smarter.</span></article><article><Image src="/images/landing/industrial-hero.png" alt="Industrial facility" fill sizes="33vw" /><b>Uptime</b><span>A brighter tomorrow.</span></article></div></section>
    <footer className="landing-v2-footer"><Brand /><nav><a href="#features">Product</a><a href="#about">About</a><a href="#benefits">Resources</a><a href="mailto:hello@maintainnexus.ai">Contact</a></nav><Link className="landing-v2-signin" href="/login">Sign In →</Link><small>© 2026 MaintainNexus AI. All rights reserved.</small></footer>
  </main>;
}
