import Link from "next/link";
import { siteContent } from "@/content/site";

export default function LandingPage() {
  return <main className="landing-shell">
    <nav className="landing-nav"><div className="brand"><span className="brand-mark">M</span><span>MAINTAIN<span className="brand-accent">NEXUS</span></span></div><div className="landing-nav-links"><a href="#story">How it works</a><a href="#proof">Why it matters</a><Link className="nav-login" href="/login">{siteContent.primaryCta}</Link></div></nav>
    <section className="landing-hero"><div className="hero-copy"><span className="eyebrow">{siteContent.eyebrow}</span><h1>{siteContent.headline}</h1><p>{siteContent.intro}</p><div className="hero-actions"><Link className="hero-primary" href="/login">{siteContent.primaryCta} <span>-&gt;</span></Link><a className="hero-secondary" href="#story">{siteContent.secondaryCta}</a></div><div className="proof-strip" id="proof">{siteContent.proof.map((item) => <div key={item.value}><strong>{item.value}</strong><span>{item.label}</span></div>)}</div></div><div className="hero-visual"><div className="signal-orbit orbit-one" /><div className="signal-orbit orbit-two" /><div className="hero-screen"><div className="screen-top"><span>THE DEPOT, RIGHT NOW</span><i>● ALL IS WELL</i></div><div className="screen-reading"><small>ONE SMALL SIGN, WORTH NOTICING</small><strong>WATCHFUL</strong><span>The machines are telling their story. We are listening.</span></div><div className="screen-bars"><i /><i /><i /><i /></div><div className="screen-foot"><span>When the moment comes</span><b>People have time to act</b></div></div><div className="floating-chip chip-risk">● A quiet warning <b>noticed</b></div><div className="floating-chip chip-audit">✓ Nothing lost to memory</div></div></section>
    <section className="slice-section" id="story"><div className="section-intro"><span className="eyebrow">ONE OPERATING LOOP</span><h2>From signal to accountable action.</h2><p>Content blocks are separated from layout so the story can evolve without rewriting the page structure.</p></div><div className="slice-grid">{siteContent.slices.map((slice) => <article className="slice-card" key={slice.eyebrow}><span className="eyebrow">{slice.eyebrow}</span><h3>{slice.title}</h3><p>{slice.text}</p><span className="slice-arrow">↗</span></article>)}</div></section>
    <footer className="landing-footer"><span>{siteContent.footer}</span><Link href="/login">Open control room -&gt;</Link></footer>
  </main>;
}
