import Link from "@/components/navigation-link";
import { requireSession } from "@/lib/session";
import { LiveUpdates } from "@/components/live-updates";
import { EquipmentState } from "@/components/equipment-monitor";
import { EquipmentTrends } from "@/components/equipment-trends";
import { EquipmentAlerts } from "@/components/equipment-alerts";
import { MaintenanceControls } from "@/components/maintenance-controls";
import { getDowntime, getEquipmentHistory, getMaintenanceData } from "@/lib/api";
import { LogoutButton } from "@/components/logout-button";

export default async function EquipmentPage({ params }: { params: Promise<{ id: string }> }) {
  const session = await requireSession(["engineer", "supervisor"]);
  const { id } = await params;
  const [history, downtime, maintenance] = await Promise.all([getEquipmentHistory(id, session.token), getDowntime(id, session.token), getMaintenanceData(session.token)]);
  const [orderResult, alertResult, roster] = maintenance;
  const orders = (orderResult.data ?? []).filter(order => order.equipment_id === id);
  const alerts = (alertResult.data ?? []).filter(alert => alert.equipment_id === id);
  const technicians = roster.data?.available_technicians ?? [];
  const readings = history.data?.readings ?? [];
  const latest = readings[readings.length - 1];
  const windows = downtime.data ?? [];
  return <main className="detail-shell equipment-workspace"><header className="detail-header"><div><span className="eyebrow">EQUIPMENT / MONITORING & RECOVERY</span><h1>{id}</h1><p>{latest?.station_id ?? "Equipment station not supplied"} ? Sensor data, failure events, and accountable maintenance.</p></div><div className="detail-actions"><Link href="/equipment">All equipment</Link><Link href="/dashboard">Station overview</Link><LiveUpdates /><LogoutButton /></div></header>
    <section className="panel monitoring-panel"><div className="panel-header"><h3>Current equipment evaluation</h3>{latest && <EquipmentState state={latest.state} />}</div>{!history.available ? <p className="notice">Equipment history unavailable. <Link href={`/equipment/${encodeURIComponent(id)}`}>Retry</Link></p> : latest ? <><div className="equipment-readings"><span>Failure probability<strong>{latest.prediction ? `${(latest.prediction.failure_probability * 100).toFixed(1)}%` : "Unscored"}</strong></span><span>Failure threshold<strong>{latest.prediction ? `${(latest.prediction.threshold * 100).toFixed(1)}%` : "Evaluation unavailable"}</strong></span><span>Last sensor reading<strong>{new Date(String(latest.telemetry.timestamp ?? latest.received_at)).toLocaleString()}</strong></span></div>{latest.evaluation_reason && <p className="notice">{latest.evaluation_reason}</p>}{latest.prediction && <p className="monitoring-context">Model risk level: {latest.prediction.risk_level}. Prediction horizon: {latest.prediction.prediction_horizon_hours} hours. This is predicted failure risk, not a confirmed physical failure.</p>}</> : <p className="empty-state">No accessible sensor history for this equipment. Health has not been established.</p>}</section>
    {history.available && <EquipmentTrends readings={readings} />}
    {alertResult.available ? <EquipmentAlerts alerts={alerts} orders={orders} technicians={roster.available ? technicians : undefined} allowAssignment={orderResult.available && roster.available} /> : <p className="notice">Failure alerts unavailable.</p>}
    <section className="panel monitoring-panel"><div className="panel-header"><div><span className="eyebrow">MAINTENANCE WORKFLOW</span><h3>Assignments & repair progress</h3></div></div><p className="monitoring-context">{roster.data?.source}</p><p className="monitoring-context">Failure alert ? assigned task awaiting approval ? dispatched ? in progress ? completed. Completing a task does not overwrite equipment readings.</p>{!roster.available && <p className="notice">Technician roster unavailable. Assignment choices cannot be loaded.</p>}{!orderResult.available ? <p className="notice">Maintenance history unavailable.</p> : orders.length ? <div className="maintenance-list">{orders.map(order => <article className="maintenance-card" key={order.work_order_id}><div className="panel-header"><Link href={`/work-orders/${encodeURIComponent(order.work_order_id)}`}><strong>{order.work_order_id}</strong></Link><span className="equipment-state">{order.status?.replaceAll("_", " ") ?? "Status unavailable"}</span></div><p>Assigned to {technicians.find(tech => tech.id === order.assigned_technician_id)?.name ?? order.assigned_technician_id ?? "Not supplied"} ? Part: {order.reserved_part ?? "Not supplied"}</p><MaintenanceControls key={`${order.status}-${order.assigned_technician_id}`} order={order} technicians={technicians} alert={alerts.find(alert => alert.task_id === order.alert_task_id)} supervisor={session.user.role === "supervisor"} /></article>)}</div> : <p className="empty-state">No maintenance tasks returned for this equipment.</p>}</section>
    <section className="panel monitoring-panel"><div className="panel-header"><h3>Downtime & recovery history</h3></div>{!downtime.available ? <p className="notice">Downtime history unavailable.</p> : windows.length ? <div className="window-list">{windows.map(window => <article key={window.id}><strong>{window.work_order_id ? <Link href={`/work-orders/${encodeURIComponent(window.work_order_id)}`}>{window.work_order_id}</Link> : "Unlinked event"}</strong><span>{new Date(window.started_at).toLocaleString()} ? {window.ended_at ? new Date(window.ended_at).toLocaleString() : "Still open"}</span><b>{window.duration_seconds == null ? "Duration unavailable" : `${Math.round(window.duration_seconds / 60)} min`}</b></article>)}</div> : <p className="empty-state">No recorded downtime windows. A window opens on dispatch and closes on maintenance completion.</p>}</section>
  </main>;
}
