import Link from "./navigation-link";
import type { EquipmentReading, Thresholds } from "@/lib/api";

export function EquipmentState({ state }: { state: string }) {
  const labels: Record<string, string> = { NORMAL: "Normal", APPROACHING_THRESHOLD: "Approaching threshold", FAILURE_DETECTED: "Failure risk detected", UNSCORED: "Awaiting evaluation" };
  return <span className={`equipment-state state-${state.toLowerCase()}`}>{labels[state] ?? state}</span>;
}

export function EquipmentMonitor({ equipment, thresholds }: { equipment: EquipmentReading[]; thresholds: Thresholds }) {
  return <section className="panel monitoring-panel"><div className="panel-header"><div><span className="eyebrow">INCOMING EQUIPMENT DATA</span><h3>Equipment monitoring</h3></div><Link href="/equipment">Open monitoring workspace →</Link></div><p className="monitoring-context">Server evaluates failure probability against {(thresholds.failure_probability * 100).toFixed(1)}% over {thresholds.prediction_horizon_hours} hours. {thresholds.warning_probability === null ? "Approaching threshold is not configured." : `Warning begins at ${(thresholds.warning_probability * 100).toFixed(1)}%.`}</p>{equipment.length ? <div className="equipment-grid">{equipment.map(reading => <Link className="equipment-card" key={reading.equipment_id} href={`/equipment/${encodeURIComponent(reading.equipment_id)}`}><div><strong>{reading.equipment_id}</strong><EquipmentState state={reading.state} /></div><small>{reading.station_id ?? "Station not supplied"}</small><div className="equipment-readings"><span>Temperature<strong>{reading.telemetry.temperature_c ?? reading.telemetry.temperature ?? "—"}{reading.telemetry.temperature_c != null ? " °C" : ""}</strong></span><span>Vibration<strong>{reading.telemetry.vibration_mm_s ?? reading.telemetry.vibration ?? "—"}{reading.telemetry.vibration_mm_s != null ? " mm/s" : ""}</strong></span><span>Failure probability<strong>{reading.prediction ? `${(reading.prediction.failure_probability * 100).toFixed(1)}%` : "Unscored"}</strong></span></div><small>Sensor time: {reading.telemetry.timestamp ? new Date(String(reading.telemetry.timestamp)).toLocaleString() : "Not supplied"}</small>{reading.evaluation_reason && <p>{reading.evaluation_reason}</p>}<span className="equipment-open">Metrics, trends & maintenance →</span></Link>)}</div> : <div className="empty-state">No equipment telemetry has been recorded in your accessible stations. Incoming sensor records will appear here.</div>}</section>;
}
