import Link from "./navigation-link";
import { CreateMaintenance } from "./maintenance-controls";
import type { RecentAlert, Technician, WorkOrder } from "@/lib/api";

export function EquipmentAlerts({ alerts, orders, technicians, allowAssignment = false }: { alerts: RecentAlert[]; orders: WorkOrder[]; technicians?: Technician[]; allowAssignment?: boolean }) {
  return <section className="panel monitoring-panel"><div className="panel-header"><div><span className="eyebrow">SERVER-GENERATED FAILURE EVENTS</span><h3>Alerts & maintenance handoff</h3></div><span>{alerts.length} recorded alerts</span></div>{alerts.length ? <div className="failure-alerts">{alerts.map((alert, index) => {
    const order = alert.task_id ? orders.find(order => order.alert_task_id === alert.task_id) : undefined;
    const prediction = alert.prediction;
    const pipelineLabels: Record<string, string> = { ALERT_QUEUE_FAILED: "Alert saved; maintenance queue unavailable", ALERT_PROCESSING: "Maintenance pipeline processing", PIPELINE_HOLD: "Maintenance pipeline on hold; check parts and services", PIPELINE_FAILED: "Maintenance pipeline failed", EXTERNAL_SOURCE_REQUIRED: "No certified technician on shift; external maintenance required", WORK_ORDER_CREATED: "Maintenance task created" };
    return <article className={`failure-alert severity-${alert.severity?.toLowerCase() ?? "unknown"}`} key={alert.task_id ?? index}><div className="failure-alert-heading"><div><Link href={`/equipment/${encodeURIComponent(alert.equipment_id)}`}><strong>{alert.equipment_id}</strong></Link><span>{alert.failure_code ?? "Failure condition received"}</span></div><span className="equipment-state">{alert.severity ?? "Severity not supplied"}</span></div><p>{prediction ? `Predicted failure probability ${(prediction.failure_probability * 100).toFixed(1)}% against a ${(prediction.threshold * 100).toFixed(1)}% threshold over ${prediction.prediction_horizon_hours} hours.` : `Backend maintenance alert.${alert.risk_probability != null ? ` Reported risk: ${(alert.risk_probability * 100).toFixed(1)}%.` : ""} Compatible threshold evaluation was not supplied.`}</p>{alert.telemetry && <div className="alert-metrics"><span>Temperature: {alert.telemetry.temperature_c ?? alert.telemetry.temperature ?? "Not supplied"}</span><span>Vibration: {alert.telemetry.vibration_mm_s ?? alert.telemetry.vibration ?? "Not supplied"}</span><span>Sensor time: {alert.telemetry.timestamp ? new Date(String(alert.telemetry.timestamp)).toLocaleString() : "Not supplied"}</span></div>}{alert.pipeline && <p className="notice">{pipelineLabels[alert.pipeline.status] ?? alert.pipeline.status.replaceAll("_", " ")}{alert.pipeline.reason ? `: ${alert.pipeline.reason}` : ""}</p>}<small>Alert received: {alert.received_at ? new Date(alert.received_at).toLocaleString() : "Not supplied"} · {alert.task_id ?? "Source ID unavailable"}</small>{order ? <p className="alert-handoff"><Link href={`/work-orders/${encodeURIComponent(order.work_order_id)}`}>{order.work_order_id}</Link> · {order.status?.replaceAll("_", " ")} · assigned to {order.assigned_technician_id ?? "Not supplied"}</p> : allowAssignment && technicians ? <CreateMaintenance alert={alert} technicians={technicians} /> : <p className="alert-handoff">No correlated maintenance task returned. Open the equipment workflow to check assignment.</p>}</article>;
  })}</div> : <div className="empty-state">No failure alerts returned by the backend.</div>}</section>;
}
