import Link from "@/components/navigation-link";
import { ActionButton } from "./action-button";
import { WorkOrderDetail } from "./work-order-detail";
import type { WorkOrder } from "@/lib/api";

export function WorkOrderQueue({ orders, status, supervisor }: { orders: WorkOrder[]; status: string; supervisor: boolean }) {
  const filtered = orders.filter(order => !status || order.status === status);
  const statuses = Array.from(new Set(["PENDING_APPROVAL", "ESCALATED", ...orders.map(order => order.status).filter((s): s is string => Boolean(s))]));
  return <><form className="filter-bar" method="GET"><label>Status<select name="status" defaultValue={status}><option value="">All statuses</option>{statuses.map(value => <option key={value} value={value}>{value.replaceAll("_", " ")}</option>)}</select></label><button type="submit">Apply filter</button><Link href="/dashboard#work-orders">Clear</Link></form><div className="order-list">{filtered.map(order => <div className="order-row" key={order.work_order_id}><span className="order-indicator" /><div className="order-main"><Link href={`/work-orders/${encodeURIComponent(order.work_order_id)}`}><strong>{order.work_order_id}</strong></Link><Link href={`/equipment/${encodeURIComponent(order.equipment_id)}`}>{order.equipment_id} / {order.reserved_part ?? "Part not supplied"}</Link>{order.risk_drivers?.length ? <div className="risk-drivers"><small>Why flagged</small>{order.risk_drivers.slice(0, 3).map(driver => <span key={driver.feature}>{driver.feature.replaceAll("_", " ")}: {driver.reason}</span>)}</div> : null}<WorkOrderDetail id={order.work_order_id} /></div><span className="status">{order.status?.replaceAll("_", " ") ?? "UNKNOWN"}</span>{order.status === "PENDING_APPROVAL" || order.status === "ESCALATED" ? <div className="row-actions"><ActionButton action="approve" workOrderId={order.work_order_id} /><ActionButton action="reject" workOrderId={order.work_order_id} />{supervisor && order.status === "PENDING_APPROVAL" && <ActionButton action="escalate" workOrderId={order.work_order_id} />}</div> : <span className="resolved-label">No review action needed</span>}</div>)}</div>{filtered.length === 0 && <p className="empty-state">No work orders match this filter.</p>}</>;
}
